#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-timeout
Version  : 1.3.3
Release  : 40
URL      : https://files.pythonhosted.org/packages/13/48/7a166eaa29c1dca6cc253e3ba5773ff2e4aa4f567c1ea3905808e95ac5c1/pytest-timeout-1.3.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/13/48/7a166eaa29c1dca6cc253e3ba5773ff2e4aa4f567c1ea3905808e95ac5c1/pytest-timeout-1.3.3.tar.gz
Summary  : py.test plugin to abort hanging tests
Group    : Development/Tools
License  : MIT
Requires: pytest-timeout-license = %{version}-%{release}
Requires: pytest-timeout-python = %{version}-%{release}
Requires: pytest-timeout-python3 = %{version}-%{release}
Requires: pytest
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
pytest-timeout
        ==============
        
        This is a plugin which will terminate tests after a certain timeout.
        When doing so it will show a stack dump of all threads running at the
        time.  This is useful when running tests under a continuous
        integration server or simply if you don't know why the test suite
        hangs.
        
        Note that while by default on POSIX systems py.test will continue to
        execute the tests after a test has timed, out this is not always
        possible.  Often the only sure way to interrupt a hanging test is by
        terminating the entire process.  As this is a hard termination
        (``os._exit()``) it will result in no teardown, JUnit XML output etc.
        But the plugin will ensure you will have the debugging output on
        stderr nevertheless, which is the most important part at this stage.
        See below for detailed information on the timeout methods and their
        side-effects.
        
        The pytest-timeout plugin has been tested on python 2.7 or higher,
        including 3.X, pypy and pypy3.  See tox.ini for currently tested
        versions.
        
        
        Usage
        =====

%package license
Summary: license components for the pytest-timeout package.
Group: Default

%description license
license components for the pytest-timeout package.


%package python
Summary: python components for the pytest-timeout package.
Group: Default
Requires: pytest-timeout-python3 = %{version}-%{release}

%description python
python components for the pytest-timeout package.


%package python3
Summary: python3 components for the pytest-timeout package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytest-timeout package.


%prep
%setup -q -n pytest-timeout-1.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542470242
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-timeout
cp LICENSE %{buildroot}/usr/share/package-licenses/pytest-timeout/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-timeout/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
